### ISSUE TITLE
Shipping Method Error 

### ISSUE THREAD

**Issue by OhHeyAlan** [vphat28/stripe-module-instantcheckout#1]
Is anyone else having a problem with Instant Checkout not working when using a shipping method other than Freeshipping? If I go to checkout using the regular checkout I can use UPS methods without a problem but in Instant Checkout the payment fails everytime.

`Magento “2.3.1”
PHP “7.2.16”
stripeofficial/module-instant-checkout “1.0.9”`

I’m getting the following error on Magento 2.3.1 using Stripe Instant Checkout (stripeofficial/module-instant-checkout) in all three locations (button, button-in-minicart, and button-in-cart)

`{"message":"Carrier with such method not found: %1, %2","parameters":["03","ups"]}`

And its from the URL

`rest/V1/guest-carts/qO37g5dXUc7cet8CsfZBSjOGnx99ANIR/shipping-information`

**Comment by vphat28** [comment]
We've published a new version for instantcheckout, please update by

composer require stripeofficial/module-instant-checkout:1.0.10 -vvv

Thank you
